config {
    type: "test",
    dataset: "authors_per_project"
}

input "cleaned" {
    SELECT 'example' AS type, "test_repo_a" AS sub_repo, (DATE '2023-03-01') AS author_date, 'bob@example.com' AS author_email UNION ALL
    SELECT 'example' AS type, "test_repo_a" AS sub_repo, (DATE '2023-03-02') AS author_date, 'alice@example.com' AS author_email
}

SELECT "example" AS type, "test_repo_a" AS sub_repo, (DATE "2023-03-02") AS last_author_date, ["bob@example.com", "alice@example.com"], "bob@example.com, alice@example.com"